Include `rcppmath` utilities in docs/FEATURES.md
ros2/rcpputils pull request #136
Opened 2021-07-15 15:32 UTC by aprotyas

The `rcppmath` utilities are not documented in `docs/FEATURES.md` file.
This PR should improve visibility. Closes #134.

Namely:
* Clamping
* Rolling mean accumulator

Signed-off-by: Abrar Rahman Protyasha <abrar@openrobotics.org>

2021-07-15 15:42 UTC, aprotyas commented
fyi @fujitatomoya

2021-07-15 15:55 UTC, clalancette requested changes
One minor change, otherwise looks good to me.

2021-07-15 15:55 UTC, clalancette commented on docs/FEATURES.md
> +This package includes convenience functions for generally cross-platform c++ functionalityand for mathematical utilties. These functionalities are siloed into the `rcpputils` and the `rcppmath` names
```suggestion
This package includes convenience functions for cross-platform c++ functionality and for mathematical utilties. These functionalities are siloed into the `rcpputils` and the `rcppmath` namespaces respectively:
```

2021-07-15 15:59 UTC, aprotyas commented
@clalancette I'm not running CI since this is just a documentation PR. Sounds good?

2021-07-15 18:11 UTC, clalancette approved these changes

2021-07-15 18:15 UTC, merged

2021-09-20 20:52 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-9-16/22372/1