Add a missing header due to missing PATH_MAX variable
ros2/rcpputils pull request #181
Opened 2023-10-06 19:10 UTC by wojciechmadry

The `xtensa-esp32` compiler does not recognize the PATH_MAX variable because the header `climits` is missing.
![missing_header](https://github.com/ros2/rcpputils/assets/108528301/3ebcf8e7-0fb8-4fd6-8bc0-1f9dd723deee)

2023-10-06 20:20 UTC, fujitatomoya approved these changes

2023-10-06 20:20 UTC, fujitatomoya commented on src/filesystem_helper.cpp
> +#include <climits>
alphabetical order?

```suggestion
#include <climits>
#include <cstring>
```

2023-10-06 20:21 UTC, fujitatomoya requested changes

2023-10-06 20:21 UTC, fujitatomoya commented on src/filesystem_helper.cpp
> +#include <climits>
change this into `Request Change`.

2023-10-06 20:26 UTC, wojciechmadry commented on src/filesystem_helper.cpp
> +#include <climits>
changed

2023-10-06 21:32 UTC, fujitatomoya approved these changes

2023-10-09 13:18 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19631)](http://ci.ros2.org/job/ci_linux/19631/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14139)](http://ci.ros2.org/job/ci_linux-aarch64/14139/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20354)](http://ci.ros2.org/job/ci_windows/20354/)

2023-10-09 18:27 UTC, merged