Included tl_expected
ros2/rcpputils pull request #185
Opened 2024-02-02 09:30 UTC by ahcorde

This PR is related with this other PR https://github.com/ros2/ros2/pull/1516

The idea is to include tl_expected in rclcpp until the standard CXX20 is available in the ros distribution

FYI @tylerjw

2024-02-02 16:15 UTC, tylerjw approved these changes
sweet, looks good

2024-02-02 17:25 UTC, clalancette requested changes
One minor change, then we can run CI on this.

2024-02-02 17:25 UTC, clalancette commented on CMakeLists.txt
> +  # find_package(ament_lint_auto REQUIRED)
Remove this please.

2024-02-02 21:45 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20216)](http://ci.ros2.org/job/ci_linux/20216/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14636)](http://ci.ros2.org/job/ci_linux-aarch64/14636/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20936)](http://ci.ros2.org/job/ci_windows/20936/)

2024-02-05 15:53 UTC, merged

2024-02-05 15:54 UTC, ahcorde commented
@clalancette can we also backport this to `humble` and `iron` ?

2024-02-06 09:41 UTC, ahcorde commented
https://github.com/Mergifyio backport humble iron